### ISSUE TITLE
preset style

### ISSUE THREAD

**Issue by aximario** [substack/highlight-javascript-syntax#1]
I hope there are some default styles in this project.
In this way, i can use these default styles directly.
These default styles can be a very popular style, such as atom-one-dark, monoka, etc.
In addition, if I think my custom style is very good, I hope to be able to share my style to everyone
So if this project can have a theme folder will be better, I can put my style to this folder :)
thanks

**Comment by substack** [comment]
I think publishing styles should happen in separate packages because people have a lot of opinions about how styles should look and I want to keep this project lean and stable. If you make a style I can link to it from this project's readme.

**Comment by tunnckoCore** [comment]
@aximario i believe it's enough to pass your style to `css` option and if you want to share it just publish the style as package with some prefix. It would be good to have some convention.

Anyway, @substack great job for the package.

**Comment by aximario** [comment]
well, I would like to write a style when I use the NPM module, and I believe that this package will help me a lot in the future. great job for the package. thanks a lot :D
